trigger:
  - main

parameters:

- name: cucumberTag
  displayName: 'Select Cucumber Tag'
  type: string
  default: '@smoke'

pool:
  vmImage: 'ubuntu-latest'

steps:

# --------------------------------------------------
# 1. Display selected tag
# --------------------------------------------------

- script: |
    echo "Selected Cucumber Tag: ${{ parameters.cucumberTag }}"
  displayName: 'Display Selected Tag'

- script: |
    echo "======================================"
    echo "SUREFIRE REPORTS"
    echo "======================================"

    find target/surefire-reports -type f -maxdepth 1 -print

    echo "======================================"
    echo "TEST REPORT CONTENT"
    echo "======================================"

    cat target/surefire-reports/*.txt || true
  condition: succeededOrFailed()
  displayName: 'Print Surefire Test Results'
# --------------------------------------------------
# 2. Setup Java
# --------------------------------------------------

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '21'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
  displayName: 'Setup Java 21'


# --------------------------------------------------
# 3. Verify Java and Maven
# --------------------------------------------------

- script: |
    java -version
    mvn -version
  displayName: 'Verify Java and Maven'


# --------------------------------------------------
# 4. Run selected Cucumber tag
# --------------------------------------------------

- script: |
    echo "Running tests with tag: ${{ parameters.cucumberTag }}"
    mvn clean test -Dheadless=true "-Dcucumber.filter.tags=${{ parameters.cucumberTag }}"
  displayName: 'Run Selenium Cucumber Tests'


# --------------------------------------------------
# 5. Publish JUnit test results
# --------------------------------------------------

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
    failTaskOnFailedTests: false
    testRunTitle: 'OrangeHRM Selenium Cucumber Tests'
  displayName: 'Publish Test Results'


# --------------------------------------------------
# 6. Publish Cucumber HTML report
# --------------------------------------------------

- task: PublishBuildArtifacts@1
  condition: succeededOrFailed()
  inputs:
    PathtoPublish: 'target/cucumber-report'
    ArtifactName: 'Cucumber-HTML-Report'
    publishLocation: 'Container'
  displayName: 'Publish Cucumber HTML Report'


# --------------------------------------------------
# 7. Publish failure screenshots
# --------------------------------------------------

- task: PublishBuildArtifacts@1
  condition: succeededOrFailed()
  inputs:
    PathtoPublish: 'target/screenshots'
    ArtifactName: 'Failure-Screenshots'
    publishLocation: 'Container'
  displayName: 'Publish Failure Screenshots'